"""Integration tests for web_extractor pipeline."""

import os
import sys
from pathlib import Path

import pytest

# Add web_extractor to path so we can import modules
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from pipeline import SearchPipeline
import generator
import structurer


@pytest.fixture
def mock_openai_to_ollama(monkeypatch):
    """Point OpenAI calls to local Ollama phi3."""
    monkeypatch.setenv("LLM_API_KEY", "ollama_key")
    monkeypatch.setattr(structurer, "USE_LLM_STRUCTURER", True)
    monkeypatch.setattr(structurer, "LLM_API_KEY", "ollama_key")
    monkeypatch.setattr(structurer, "LLM_MODEL", "phi3")

    # Mock the OpenAI client in generator to use Ollama endpoint
    original_init = generator.ContentGenerator.__init__
    
    def mocked_init(self):
        original_init(self)
        try:
            from openai import OpenAI
            self.client = OpenAI(
                base_url="http://localhost:11434/v1", 
                api_key="ollama"
            )
            self.model = "phi3"
            self.has_api = True
        except ImportError:
            self.has_api = False
            
    monkeypatch.setattr(generator.ContentGenerator, "__init__", mocked_init)
    
    import openai
    openai.api_base = "http://localhost:11434/v1"
    
    yield


@pytest.mark.integration
def test_pipeline_with_phi3(mock_openai_to_ollama):
    """Run extraction pipeline using phi3 inference."""
    pipeline = SearchPipeline(use_cache=False)
    
    # Run with simple query and only 1 result to keep tests fast
    result = pipeline.run("What is Pytest test automation?", max_results=1)
    
    assert result is not None
    assert result["query"] == "What is Pytest test automation?"
    assert "results" in result
    
    # Check if AI content generated by our Ollama fallback
    assert "ai_generated_summary" in result
    summary_len = len(result["ai_generated_summary"])
    assert summary_len > 0
    
    # Check pipeline captured at least 1 document structure snippet
    assert len(result["results"]) > 0
